
export default {

    LOGIN_START:"LOGIN_START",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_ERROR:"LOGIN_ERROR",

    CLEAR_STORAGE : 'CLEAR_STORAGE',
    SET_PHONENUMBER : "SET_PHONENUMBER",
    SET_PROFILE : "SET_PROFILE",
    GET_OTP : "GET_OTP",
    EDITING_LOCATION : "EDITING_LOCATION",
    PROFILE_MODAL_VISIBLE : "PROFILE_MODAL_VISIBLE",
    OPEN_MODAL : "OPEN_MODAL",
}