
export default {
    EXHIBITION_FORM: "EXHIBITION_FORM",
    EDIT_EXHIBITION_MODE: "EDIT_EXHIBITION_MODE",
    EDIT_CONTENT_MODE : "EDIT_CONTENT_MODE",
    EXHIBITION_ID: "EXHIBITION_ID",
    REDUX_SELECTED_ARTWORKS: "REDUX_SELECTED_ARTWORKS",
}