
export default {
    GALLERY_ID: "GALLERY_ID",
    EXHIBITION_ID: "EXHIBITION_ID",
    GALLERY_PROFILE: "GALLERY_PROFILE",
    SELECTED_ARTWORKS: "SELECTED_ARTWORKS",
    EDIT_GALLERY_MODE: "EDIT_GALLERY_MODE",
    EDIT_EXHIBITION_MODE: "EDIT_EXHIBITION_MODE",
}