
export default {

    // LOGIN_START:"LOGIN_START",
    // LOGIN_SUCCESS:"LOGIN_SUCCESS",
    // LOGIN_ERROR:"LOGIN_ERROR",

    // CLEAR_STORAGE : 'CLEAR_STORAGE',
    // SET_PHONENUMBER : "SET_PHONENUMBER",
    // SET_PROFILE : "SET_PROFILE",
    // GET_OTP : "GET_OTP"

    ARTWORK_FORM : "ARTWORK_FORM",
    ARTIST_FORM : "ARTIST_FORM",
}